### ISSUE TITLE
Some bugs/issues I faced while using this amazing tool 

### ISSUE THREAD

**Issue by Jonnie-Dev** [AliReza1083/Twitter-Profile#1]
Profiles with long text bios tends to overflow their specified container. 
![Screenshot_2023-02-03-22-56-12-601_com android chrome](https://user-images.githubusercontent.com/73708569/216718713-f5f2c8c0-99a9-4cb6-bcc9-bd342df85c51.png)

Also on mobile, it seems that the download menu is hidden, I have to switch to desktop mode everytime I need to save the profile image. 
![Screenshot_2023-02-03-22-56-44-236_com android chrome](https://user-images.githubusercontent.com/73708569/216719111-3d5ba60e-3edb-4b00-94df-15355c040a33.png)

Above all amazing initiative, amazing tool, great work Ali 🙌

**Comment by AliReza1083** [comment]
Thanks for the issue...
We will solve the problem soon.

**Comment by AliReza1083** [comment]
The issue with the navbar has been fixed, but about the text, There might be a problem with the text itself.
They didn't put any space between them, that's why It is not working well.

This one is working fine.
![image](https://user-images.githubusercontent.com/99729607/216723922-c48b33ac-70d2-4e92-98fb-81bf80111909.png)
